### ISSUE TITLE
How to manage API keys with clientside code

### ISSUE THREAD

**Issue by philipashlock** [uscensusbureau/citysdk#108]
Since the CitySDK is currently focused on a front-end javascript code and it requires a Census API key, it seems like the only way to use CitySDK for public applications is to expose your API key to the public. Often API keys are designed to be restricted to specific servers/referrers. That might be one way to address the potential for abuse given the current situation which effectively requires everyone using CitySDK to share their API keys with the world.

**Comment by afrasier** [comment]
I agree, @logantpowell , can you bring this up with the API team?

**Comment by logantpowell** [comment]
Will do. Good lookin' out

**Comment by logantpowell** [comment]
From a lead on the team:

"It's true that when used inside frontend JavaScript an API key is exposed via the JavaScript source code.  A good way to side-step this issue is for a developer to setup her own webservice.  She can send all of her API calls (without an API key) to that webservice and have that service add the API key and forward the request to api.census.gov.  This is what the My Congressional District app does, for example. There is no need to restrict an API key to a specific server or referer (sic) which may be forged."

**Comment by loganpowell** [comment]
v2 is an NPM library, so you can use `dotenv` for this
