### ISSUE TITLE
Enable easy retrieval of data for every block group within a city (Census Place)

### ISSUE THREAD

**Issue by tyronegrandison** [uscensusbureau/citysdk#112]
From Forest Gregg:

The container interface only is present for GeoJSON. Very often, I want to get data for every block group within a city (Census Place). This interface means that I have to download the geographies each time I want an additional piece of information.

@logantpowell @jmeisel Arman says that this is a CENSUS API issue.

**Comment by afrasier** [comment]
Census geographies don't align perfectly with city boundaries - thus, there's no hierarchical structure to define which block groups/tracts/etc. are within a city. This is why we have to grab the boundaries for the city and use the TigerWeb server to find all block groups that are within or intersect.

**Comment by logantpowell** [comment]
Arman is right, but I'm not even sure what Forest is asking for...

**Comment by afrasier** [comment]
Basically he wants to tell the ACS api "Give me the population of every block group within place 4000 in state 04"; but like we noted this can't be done because a place's geography doesn't fit in the census hierarchy. We have to use the boundary geographies as a request polygon to Tigerweb to get all of the Census block groups. 

I could write a function that doe the request and throws away the geography, but that might be kind of pointless as the users would still be using the bandwidth for the geography, just throwing away that extra data when they get it.

**Comment by logantpowell** [comment]
@tyronegrandison can you tell him to do what @afrasier is recommending (i.e., use the custom boundary function with a census place to pull down the overlapping+nested boundaries)?
