### ISSUE TITLE
Make "within" container mode have some tolerance

### ISSUE THREAD

**Issue by stevevance** [uscensusbureau/citysdk#141]
These two screenshots shows the result of when I send my containing geometry and ask for the container mode of "geometry" (intersects) and "within". The containing geometry is a Chicago community area called Avondale. The boundaries of Chicago community ares do not change and for the most part line up with Census tracts. 

![screenshot 2015-06-24 01 47 48](https://cloud.githubusercontent.com/assets/1330459/8324209/a211d260-1a13-11e5-8b02-b504fb478617.png)
![screenshot 2015-06-24 01 48 12](https://cloud.githubusercontent.com/assets/1330459/8324213/a6f54e42-1a13-11e5-978c-16ffedeb3c12.png)

Is it possible to set a tolerance mode that will return the Census tracts that are "mostly" within the containing geometry? (This image shows how the borders are essentially the same but drawn with errors.)

![screenshot 2015-06-24 01 52 01](https://cloud.githubusercontent.com/assets/1330459/8324214/ab4dacb4-1a13-11e5-8d50-168adca5fc2d.png)

**Comment by afrasier** [comment]
@stevevance, are the results any better if you use "geometry" instead of "geometry_within" - since your borders are so close to the Census boundaries it might play nicer. The algorithms for within/intersects are part of the ArcGIS server. It might be worth adding extra intersect modes directly selectable by users in the future. I went ahead and made an issue for that. (#142)

**Comment by stevevance** [comment]
@afrasier The screenshots show the difference in using the geometry & geometry_within parameters. Within is too explicit (restrictive) and excludes too many tracts or block groups to make it useful. Thanks for making the new issue!
