### ISSUE TITLE
zipcode data elements

### ISSUE THREAD

**Issue by rbender30** [uscensusbureau/citysdk#143]
Hi,

I am looking to create something similar to the zip code example (https://github.com/uscensusbureau/citysdk/blob/master/examples/zipCodeExample/index.html).

Do you have a listing / library for all of the elements that can be returned? For example .. here you return Income and Population .. what would be the other options?

Thanks,
Rachel

**Comment by afrasier** [comment]
Rachel,

You can use any ACS variable codes (available through http://www.census.gov/data/developers/data-sets/acs-survey-5-year-data.html - check out the list of variables, available in json, html, and xml). In the example, we make use of the SDK's alias feature. This feature provides simple names for commonly used variable codes, so that one doesn't have to look them up.

For more documentation on aliases, see http://uscensusbureau.github.io/citysdk/guides/censusModule.html#variableAliases

For a full list of aliases, see
http://uscensusbureau.github.io/citysdk/guides/censusModule/aliases.html

**Comment by rbender30** [comment]
Thank you!
