### ISSUE TITLE
Zip categorization

### ISSUE THREAD

**Issue by rbender30** [uscensusbureau/citysdk#144]
Hi,

I am working with the data on 
http://api.census.gov/data/2013/acs5/variables.json

Is there a way to categorize this data into a hierarchy? 

Thanks!
Rachel

**Comment by afrasier** [comment]
The easiest way is to use Census Reporter's Explore feature ( http://censusreporter.org/ ) to look for variables you are interested in.

There is currently no built in functionality to categorize the entire ACS variable dictionary.

**Comment by rbender30** [comment]
Thanks for the quick reply! You may have addressed this in your note above, but I just wanted to confirm since my first question was sort of vague:

Is there a programmatic representation of this page?
http://censusreporter.org/topics/

We want to programmatically collect the topics, then programatically collect the topic attributes, here as an example (http://censusreporter.org/topics/income/ ).

While we could scrape the contents of the pages, we want to avoid a 'hack' if there is a better option available.

This page ( http://www.census.gov/data/developers/data-sets/acs-survey-5-year-data.html ) links to a json page ( http://api.census.gov/data/2013/acs5/variables.json ). We're looking for a similar representation of the topics and their attributes.

**Comment by afrasier** [comment]
Unfortunately, nothing is implemented in the SDK for this. (And this issue is part of the root of why the Census module was created in the first place)

The variables DO follow a pattern, that is, certain tables (the part before the underscore) and data points (the part after the underscore) are similar.

If you take a look at the alias list (http://uscensusbureau.github.io/citysdk/guides/censusModule/aliases.html) you can kind of see these patterns. Table B17001 provides information on poverty, and adding a suffix to the table changes the demographic (e.g. B17001A gives you a table for white responses, B17001D gives you a table for Asian responses).

I am not an expert on the ACS nor have I seen all of the variable codes so I can't vouch that there is a system that would be easy to handle programmitcally. You might try chatting with the Census reporter (I believe their code is on github as well) regarding how they went about it.

**Comment by rbender30** [comment]
Thank you! That's really helpful

Rachel Bender | Arjuna Solutions
(240) 731-8067

On Jun 26, 2015, at 20:53, Arman Frasier <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately, nothing is implemented in the SDK for this. (And this issue is part of the root of why the Census module was created in the first place)

The variables DO follow a pattern, that is, certain tables (the part before the underscore) and data points (the part after the underscore) are similar.

If you take a look at the alias list (http://uscensusbureau.github.io/citysdk/guides/censusModule/aliases.html) you can kind of see these patterns. Table B17001 provides information on poverty, and adding a suffix to the table changes the demographic (e.g. B17001A gives you a table for white responses, B17001D gives you a table for Asian responses).

I am not an expert on the ACS nor have I seen all of the variable codes so I can't vouch that there is a system that would be easy to handle programmitcally. You might try chatting with the Census reporter (I believe their code is on github as well) regarding how they went about it.

-

**Comment by logantpowell** [comment]
@rbender30 I'm copying our incredible friend @joegermuska who is the lead on the Census Reporter project. I know they've paid a significant amount of attention to the discovery challenge in the ACS variable ocean...

**Comment by rbender30** [comment]
Thanks! We are really excited about the sdk, as we haven't been able to gather census data like this before. The icing on the cake would be the categorization.

Rachel Bender | Arjuna Solutions
(240) 731-8067

On Jun 29, 2015, at 07:30, Logan <notifications@github.com<mailto:notifications@github.com>> wrote:


@rbender30<https://github.com/rbender30> I'm copying our incredible friend @joegermuska<https://github.com/joegermuska> who is the lead on the Census Reporter project. I know they've paid a significant amount of attention to the discovery challenge in the ACS variable ocean...

-

**Comment by logantpowell** [comment]
I know it's not the perfect solution, but have you tried: http://api.census.gov/data/2013/acs5/tags.html ?
You can also replace the ".html" with ".json"
