### ISSUE TITLE
Why does citysdk have a cache system?

### ISSUE THREAD

**Issue by tmcw** [uscensusbureau/citysdk#206]
https://github.com/uscensusbureau/citysdk/blob/0a8f6ef40d392d0070bd80deb6b5c48c0d64bbe0/js/citysdk.js#L19-L51

CitySDK contains its own cache system. Why is this? There's no [discussion of the cache system](https://github.com/uscensusbureau/citysdk/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+cache), and browsers have their own request caches with more sophisticated rules and broader support than a hand-rolled request cache. Can this be removed?

**Comment by johnson-tor-boozallen** [comment]
In watching the browser behavior, there was a large number of cases where it was consistently re-requesting similar content from the APIs which were often re-transmitting the data instead of submitting the customary 304 response that would indicate that data can be re-used.  This meant that the browsers were often being pre-empted from using their native caches as expected.

The caching system can be disabled if desired (new manuals reflecting all the new features, including how implementors of the library can turn the cache off are being presently updated and released later this week).

**Comment by tmcw** [comment]
> In watching the browser behavior, there was a large number of cases where it was consistently re-requesting similar content from the APIs which were often re-transmitting the data instead of submitting the customary 304 response that would indicate that data can be re-used

This is a symptom of incorrectly configured servers: this error should be considered something to fix upstream, not paper over in an SDK. Ideally the authors of CitySDK can talk to the orgs running the endpoints and get them to support caching properly, so that _any_ REST client will benefit.

**Comment by logantpowell** [comment]
"... Ideally the authors of CitySDK can talk to the orgs running the endpoints and get them to support caching properly, so that any REST client will benefit."

Completely agree... We have been trying to do this for some time now.
