### ISSUE TITLE
Incorporate data from earlier censuses

### ISSUE THREAD

**Issue by thecristen** [uscensusbureau/citysdk#240]
At the very least, 1980 seems to be available [here](http://www2.census.gov/)

**Comment by logantpowell** [comment]
Hi @thecristen! it'll have to be added to our DataWeb API in order for CitySDK to have access to it. For that to happen, please email cnmp.developers.list@census.gov with the request. I can't make any promises, but if there's a voiced demand from users, it could get prioritized :)

**Comment by thecristen** [comment]
Thanks @logantpowell I'll do so! In the meantime feel free to close this issue if it suits you. :)

**Comment by logantpowell** [comment]
For posterity, here's the answer from the "inside":

Hi Cristen. 

We love connecting older datasets together too! We are working to get as many historical and time series datasets in the API as we can, but our primary goal is getting all of the current data processed first because the API is becoming so important to the way Census distributes our own data. 

Older data requires tremendous resources to find machine readable files, and then review them so it is a struggle but we're working on .

Right now we have a few datasets that might be interesting: 

http://api.census.gov/data/timeseries.html 
http://api.census.gov/data/bds.html

The poverty data goes back to the 1950s as does the International database. Business Dynamics also goes back to the 1970s. 

We're also working with population estimates program on setting up some historical intercensal estimates datasets. Right now we're only working on the 1990's and 2000's but after that they may find time to work on the older decades.

If you identify machine readable files (csv, excel etc.) on census.gov that you'd really like to see in the API, those are the easiest for us to accomplish and I'd be happy to contact the product owners and let them know there is some demand for those.

Thanks for your feedback,

Tiffany

Tiffany Julian

301-763-4137 

DataWeb Applications

US Census Bureau
