### ISSUE TITLE
Provide 1990 geographies

### ISSUE THREAD

**Issue by fgregg** [uscensusbureau/citysdk#324]
The census API provides data going back to 1990 for SF3. It'd be great if 1990 geographies could also be provided so that long time series.

**Comment by loganpowell** [comment]
@fgregg I've brought this up with our team and - unfortunately - since there was a large effort to get the 2000+ geographies into Tigerweb when the team migrated and the older files were not compatible with the migration, these older vintages are not planned for inclusion in the near future. We will continue to pursue options for including these in the future and I will let you know if anything changes, but - in the meantime - IPUMS has files you may find useful: https://www.nhgis.org/documentation/gis-data signing up for an account is really quick and free.

**Comment by loganpowell** [comment]
@fgregg 

We've got a new version of CitySDK ready for open beta testing if you'd like to give it a go. It's an NPM library now, so it should work on your Node server or in the browswer (via Browserify, Webpack, etc.).

This version includes 1990 Cartographic GeoJSON. You can find out more in the Readme:

https://github.com/uscensusbureau/citysdk#census-cartography-files-in-geojson-format

There are a few examples you can play with here (if you don't have a Node environment handy):

https://uscensusbureau.github.io/citysdk/examples/

Note that in a couple examples, I'm using Runkit, which has about a 10x throttle on requests, so it's more for playing with small examples. It doesn't represent what can be done in terms of performance.
