### ISSUE TITLE
Cannot use FIPS codes in geoHierarchy?

### ISSUE THREAD

**Issue by rybesh** [uscensusbureau/citysdk#343]
I would expect the following query to return all counties in North Carolina:
```js
{
  vintage: 2018,
  geoHierarchy: {
    state: '37',
    county: '*',
  },
  geoResolution: '20m'
}
```
Instead, it seems to return all counties, period. Why?

**Comment by loganpowell** [comment]
In order to scope a citysdk geojson response down to something other than
how it is stored, you will have to provide a statistics argument, that -
upon merge with the geojson - will scope your request. I.e., Counties are
stored at the national level. In order to get back just one state, try
something like this:

{
  vintage: 2018,

  sourcePath: ["acs", "acs1"],
  geoHierarchy: {
    state: '37',
    county: '*',
  },

  values: ["NAME"],
  geoResolution: '20m'
}


You can read more in the README:
https://github.com/uscensusbureau/citysdk#notable-example

**Comment by rybesh** [comment]
OK, I see that I didn't read this part carefully enough:

> It's important to note that - when querying for these GeoJSON files - you may retrieve a larger area than your request argument specifies. The reason for this is that the files are (currently) stored at two geographic levels: National and by State.

Thanks!
