### ISSUE TITLE
rename to `U.S. City SDK`

### ISSUE THREAD

**Issue by rebeccawilliams** [uscensusbureau/citysdk#88]
to distinguish from the [European City SDK](http://www.citysdk.eu/about-the-project/) and be more discoverable via search engines.

**Comment by ajturner** [comment]
@rebeccawilliams indeed, however the libraries and references would still be to 'CitySDK'. So is it better to take over the search engine rankings - particularly since the original CitySDK.eu seems deprecated (or at least stagnant). 

Generally, the European vs. U.S. have different technical concepts but the same vision. Neither are limited to national or continental boundaries. So there could be CitySDK-UKCensus or CitySDK-EU-Census modules.

**Comment by logantpowell** [comment]
Thank you guys for this discussion. We are a little wed to the current name, but we have had discussions about this particular issue (with the EU) and will bring these recommendations with us next time the topic of discussion comes up.
